version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      
      # debug
      - run: cd ./sahi && pwd && ls
      
      # test
      - run: cd ./sahi && ant -buildfile build.xml