version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      
# Debug - Verify Ant version
      - run: ant -version
    
# Debug
      - run: pwd && ls -r
         
# Run tests - Playback via ant
      - run: ant -f build.xml