version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: pwd
      - run: ls -R
      
# Copy the Sahi Pro installer jar to the desired location.
      - run: wget http://sahipro.com/static/builds/pro/install_sahi_pro_v750_20171222.jar
      - run: mv install_sahi_pro_v750_20171222.jar sahi

# Debug
      - run: ls -R
      - run: java -version

# Debug
      - run: cd /home/circleci/project/sahi
      - run: pwd
      - run: ls
      
# Install Sahi Pro using the following command
      - run: java -jar install_sahi_pro_v750_20171222.jar silent_install.xml

# Start Sahi Pro 
      - run: cd /home/circleci/project/sahi/userdata/bin
      - run: ./start_sahi.sh
