version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

# Prepare environment for sshpass
      - run: sudo rm /var/lib/apt/lists/lock || true
      - run: sudo apt-get clean && sudo apt-get update && sudo apt-get install sshpass -f 

# Run a step to execute multiple commands on server via sshpass
      - run:
          command: |
            sshpass -p $AUTHENTICATION ssh -o StrictHostKeyChecking=no Administrator@18.130.251.90 "cd C:\Program Files\Git\bin && start sh.exe"
            sshpass -p $AUTHENTICATION ssh -o StrictHostKeyChecking=no Administrator@18.130.251.90 "cd C:/Users/Administrator/Documents/GitHub/circleci-sahi && git pull origin master";
            sshpass -p $AUTHENTICATION ssh -o StrictHostKeyChecking=no Administrator@18.130.251.90 "cd C:/Users/Administrator/Documents/GitHub/circleci-sahi && testSahi.bat"